### ISSUE TITLE
conflicting information on 64-bit Linux compatibility

### ISSUE THREAD

**Issue by jeffythedragonslayer** [alekmaul/pvsneslib#133]
I'm finding conflicting information on whether or not PVsneslib is currently compatible with 64-bit Linux.

https://github.com/alekmaul/pvsneslib/wiki says no,
but the asset on https://github.com/alekmaul/pvsneslib/releases/tag/4.0.1 is called
Linux-x64-401-release.zip

**Comment by RetroAntho** [comment]
I agree with you and discussed this point with @alekmaul. It is mentioned x64 in linux version because it is built from an OS 64b version.
In fact, the 32b informations for pvsneslib is only provided for Mac OS which does not support 32b architecture anymore if i understood correctly. It does not have impact for linux or windows.
We will probably review this point soon when working on Mac OS version

**Comment by alekmaul** [comment]
yes, it is correct. No bug at all regarding this issue
