### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by jeffythedragonslayer** [alekmaul/pvsneslib#135]
In http://www.portabledev.com/pvsneslib/doc/a00575.html,

The T_SPIKE #define is documented as "Spyke"

**Comment by RetroAntho** [comment]
Hi,

Thanks for the merge request. I saw you created it on master branch. This kind of update should be 1st sent to develop branch and merged in master during release version only.

I propose to keep the issue related opened because because i saw some other gaps :
- T_LADDE should be T_LADDER : https://github.com/alekmaul/pvsneslib/search?q=T_LADDE
- Does T_PLATE should be T_GROUND ? (or the comment is not updated) : https://github.com/alekmaul/pvsneslib/search?q=T_PLATE

it is more easy to follow if we regroup them

**Comment by alekmaul** [comment]
I will update Ladder but not plate, i will update the comment
