### ISSUE TITLE
regex.h not available on Windows

### ISSUE THREAD

**Issue by daniel-starke** [alekmaul/pvsneslib#224]
816-opt in the develop branch uses `regex.h` from [libtre](https://github.com/GerHobbelt/libtre) which is no longer maintained.
I suggest moving to [PCRE2](https://github.com/PCRE2Project/pcre2) which provides a drop-in replacement with `pcre2posix.h` and `libpcre2-posix.a`.
Note, however, that PCRE2 requires `PCRE2_STATIC` to be defined when linking statically.
I suggest defining this in the Makefile if Windows was detected as target and include `pcre2posix.h` instead of `regex.h` in `helpers.h` if `PCRE2_STATIC` was defined.

**Comment by kobenairb** [comment]
Hello @daniel-starke, may I ask how you want to proceed? If I understand correctly we go from regex.h to pcre2posix.h and libpcre2-posix.h. So that means modifying the regexMatchGroups function to use pcre2, modifying the Makefile to update the compilation options. Can I ask you to do a PR for this? I have a version of regexMatchGroups under pcre but not pcre2.

**Comment by RetroAntho** [comment]
Thanks for the fix, i guess i can close the issue? Please tell me if i am wrong :)
