### ISSUE TITLE
CHECK HEADER: files from different projects

### ISSUE THREAD

**Issue by lepusagri** [alekmaul/pvsneslib#3]
If i try to link one of the examples, i get this error message. What can i do to solve it?

**Comment by alekmaul** [comment]
Yes, I think it is because examples are still with configuraiton of a SRAM project and no more the lib.
I will update the hdr.asm file of each example.
If you want to do that on your side to unblock you, just change this part in hdr.asm file :
  CARTRIDGETYPE $02             ; $02 = ROM+SRAM, see WLA documentation for others
  ROMSIZE $08                   ; $08 = 2 Mbits,  see WLA doc for more..
  SRAMSIZE $01                  ; $01 = 16 kbits, see WLA doc for more..
  COUNTRY $01                   ; $01 = U.S.  $00 = Japan, that's all I know
  LICENSEECODE $00              ; Just use $00
  VERSION $00                   ; $00 = 1.00, $01 = 1.01, etc.

to 
  CARTRIDGETYPE $00             ; $00 = ROM
  ROMSIZE $08                   ; $08 = 2 Mbits,  see WLA doc for more..
  SRAMSIZE $00                  ; $00 = No SRAM.
  COUNTRY $01                   ; $01 = U.S.  $00 = Japan, that's all I know
  LICENSEECODE $00              ; Just use $00
  VERSION $00                   ; $00 = 1.00, $01 = 1.01, etc.

**Comment by lepusagri** [comment]
Thank you.

Most of the examples work now.

Only the game likemario can't be build.

The wlalink.exe crashes.

Maybe you can find out the cause of the problem.


Best regards,

Thomas Hasenecker



Am 04.06.2017 um 06:20 schrieb alekmaul:

**Comment by alekmaul** [comment]
ok, will check it tomorrow
