### ISSUE TITLE
SA-1 example

### ISSUE THREAD

**Issue by odelot** [alekmaul/pvsneslib#31]
Hi. Is there any chance to see a SA-1 example using the pvsneslib? I would donate with other users to see this feature on the lib ^.^ thank you for your great work!

**Comment by alekmaul** [comment]
sorry for the lack of news. Currently, I really don't know how to add SA-1 feature, do you have any spec about this chipset ?

**Comment by hoit** [comment]
With the upgrade of wla version, it become now possible to manage this kind of chipset. The wla repository contains some tickets to improve functionalities about it and i think we need to wait on it.
i think we can close this issue because the roadmap contains a point about this improvement ?(but it will not be treated soon)
