### ISSUE TITLE
Error with unresolved "Soundbank" 

### ISSUE THREAD

**Issue by rnbastos** [alekmaul/pvsneslib#74]
Hello. I'm just trying to compile an old project that, from a friend, I know it worked in older release of PVSNESLIB.
But now, I have this strange issue:

sor2.obj: sor2.asm:9753: PARSE_STACK: Unresolved reference to "__SOUNDBANK__1".

The variable seems to be correct, I see the soundbank.h / soundbank.asm are built "correctly" with soundbank0 and soundbank1, but in the end, this error always comes... What exactly could have changed that I still didn't fix for this release?

**Comment by rnbastos** [comment]
Hmmmm.. Just noticed this... no idea of why it's being discarded

DISCARD: soundbank.obj: soundbank.asm: Section "SOUNDBANK1" was discarded.

It happens with bank 0 too.

**Comment by rnbastos** [comment]
Ahhhh nevermind. I did a full change in the way that project was being built, changed variables, and lots of stuff in makefile.
Now it compiles, with sound.
Some images are not correct but I'll understand that as bugs in the project.

**Comment by malayli** [comment]
@rnbastos How did you solve this issue? What are the changes in the Makefile?

**Comment by RetroAntho** [comment]
for the error 
`sor2.obj: sor2.asm:9753: PARSE_STACK: Unresolved reference to "__SOUNDBANK__1".`
it is because the project has been created with pvsneslib v2.
Now with the new version (pvsneslib v3), you have to remove the first underscore (otherwise WLA create a local item).
__SOUNBANK__1 should become SOUNBANK__1

For other changes in makefiles, i think it is also related to the move from v2 to v3 (which have cleaner makefile).

**Comment by rnbastos** [comment]
hi! yeah, the change that I made, and really made difference was changing __SOUNBANK__1  to SOUNBANK__1 
I think I did other changes but for the sound problem, the variable naming was the problem.

**Comment by alekmaul** [comment]
ok, I close the issue
