### ISSUE TITLE
Mac Version

### ISSUE THREAD

**Issue by maxoakland** [alekmaul/pvsneslib#87]
Seems like a Mac version might be possible since it already requires a UNIX-like environment for Windows. I’d be interested in trying this out but I don’t have a PC or Linux

**Comment by alekmaul** [comment]
OK, but I don't know what I can do for you. I prefer closing the issue. If you want help on Mac, try pvsneslib discord

**Comment by RetroAntho** [comment]
Hi,
@maxoakland, i do not have Mac but if you can build it yourself it could be a good point. Do you think you can do it by following this tutorial ?
https://github.com/alekmaul/pvsneslib/wiki/Compiling-from-sources

Just a remark about pvsneslib which is only 32bits compatible for now due to limitations in our tcc version. I believe that the last Mac OS version are only 64 bits.

**Comment by maxoakland** [comment]
Oh true. I do have Mojave which can still run 32bit software so maybe I’m in luck! I’ll try compiling it but I have never had much luck doing that
