### ISSUE TITLE
How to use the VS Code Template on Linux?

### ISSUE THREAD

**Issue by YusufSuleman** [alekmaul/pvsneslib#88]
How to use the VS Code Template on Linux? The README only talks about a wiki page for Windows and the VS Code page on the Wiki only talks about Windows.

**Comment by RetroAntho** [comment]
It is the same on Windows or Linux, you just need to update the c_cpp_properties.json file (pvsneslibPath) with the path where you installed it.
The wiki page "installation with windows" will be rewrite soon to be more generic (and because the new pvsneslib release which will be available soon will be more easy to install)
but the page for visual studio code is not only for windows :
https://github.com/alekmaul/pvsneslib/wiki/PVSneslib-and-Visual-Studio-Code

Instead of having 
`"pvsneslibPath": ["c:/pvsneslib/pvsneslib/include/**","c:/pvsneslib/devkitsnes/include"],`
you will have something like :
"pvsneslibPath": ["/you/path/to/pvsneslib/pvsneslib/include/**","//you/path/to/pvsneslib/devkitsnes/include"],
